name = "fear-social"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
NOTIFICATION_EMAIL = "tsbrown223@gmail.com"
EMAIL_FROM = "fear.social <notifications@fear.social>"

[[d1_databases]]
binding = "DB"
database_name = "fear-social-db"
database_id = "046cdb1b-68c0-45c4-b4a6-e9e40d980bfa"
migrations_dir = "migrations"
