INSERT OR IGNORE INTO users (
  id,
  token,
  name,
  handle,
  email,
  location,
  industry,
  stage,
  bio,
  privacy,
  avatar_url,
  role,
  headline,
  website,
  looking_for,
  goal,
  verified_badge,
  email_verified_at
)
VALUES (
  'fear-social-official',
  'official-fear-social-official',
  'fear.social',
  '@fear.social',
  'official@fear.social',
  'Remote',
  'Community',
  'Building',
  'Official fear.social account for daily prompts, product updates, and first-step momentum.',
  'public',
  'https://fear.social/fear-official-avatar.png',
  'admin',
  'Official fear.social daily reels and platform notes.',
  'https://fear.social',
  'People ready to take their first business or career step.',
  'Turn fear into momentum.',
  1,
  CURRENT_TIMESTAMP
);

UPDATE users
SET name = 'fear.social',
    handle = '@fear.social',
    email = 'official@fear.social',
    location = 'Remote',
    industry = 'Community',
    stage = 'Building',
    bio = 'Official fear.social account for daily prompts, product updates, and first-step momentum.',
    privacy = 'public',
    avatar_url = 'https://fear.social/fear-official-avatar.png',
    role = 'admin',
    headline = 'Official fear.social daily reels and platform notes.',
    website = 'https://fear.social',
    looking_for = 'People ready to take their first business or career step.',
    goal = 'Turn fear into momentum.',
    verified_badge = 1,
    email_verified_at = COALESCE(email_verified_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = 'fear-social-official';
