ALTER TABLE users ADD COLUMN avatar_position_x REAL NOT NULL DEFAULT 50;
ALTER TABLE users ADD COLUMN avatar_position_y REAL NOT NULL DEFAULT 50;
ALTER TABLE users ADD COLUMN cover_position_x REAL NOT NULL DEFAULT 50;
ALTER TABLE users ADD COLUMN cover_position_y REAL NOT NULL DEFAULT 50;
